### ISSUE TITLE
 Rendering of the edges seems to work only in a certain area

### ISSUE THREAD

**Issue by SchmiedHammer** [borkdominik/bigER#29] opened 2022-09-21 16:24 UTC
The rendering of the edges seems to work only in a certain area of the diagram view. In the
screenshot, the entity E1 was dragged to the left side of the diagram view until the circle
on the end of the edge started to disappear. It appears this phenomenon is in relation to the size
of the initially rendered diagram.

<img width="218" alt="image" src="https://user-images.githubusercontent.com/51507817/191557365-0b840e0b-4814-4493-958f-792e1d0341a8.png">

**Comment by Aksem** [comment] 2022-09-22 14:09
@SchmiedHammer, could you please help to reproduce this problem? I've checked the current main and #27 and couldn't find a view with circles.

**Comment by SchmiedHammer** [comment] 2022-09-22 15:58
The circle is part of the Bachman notation. You can use the following BasicExample for the textual editor to reproduce the issue, but the problem is not only restricted to the circle of the Bachman notation. Every notation with a custom rendering (Crow's Foot, Bachman, UML) has the same problem when the elements of the diagram are moved apart.

erdiagram BasicExample // ER model
notation=bachman

// entities
entity Customer {
    id: int key
    name: string
}
entity Order {
    order_number: int key
    price: double
}

// one-to-many relationship
relationship Places {
    Customer[1] -> Order[1] 
}

**Comment by Aksem** [comment] 2022-09-22 17:48
I've got it.
First, the problem is not related to the routing of edges because routes are always correct, and they are also rendered correct (even if a circle disappears, a line is still fully visible), but to "edge additions" like circles. They begin to disappear if we move them so that at least one of the coordinates is negative.
The reason is that they are wrapped in `<svg>` element, which defines a new viewport and shows children with only positive coordinates by default.
If you wrap the elements only to group them, I would recommend using `<g>` instead(it works, tested). If you need some features of `<svg>`, then it needs additional parameters to solve the problem. One working workaround is setting 'overflow: visible' for `<svg>`, but I don't think it's a good idea, only if it's one working solution.

**Comment by plglaser** [comment] 2022-12-20 19:13
Thanks for pointer, the issue was indeed fixed by wrapping the views in `<g>` instead of `<svg>` tags (e.g., [see here](https://github.com/borkdominik/bigER/blob/main/webview/src/views.tsx#L210)).

The fix for this bug is already available in the latest release, thus, the issue is closed.

**Closed by plglaser** 2022-12-20 19:13 UTC
Labels: bug
